### ISSUE TITLE
Question about DNS API Aruba

### ISSUE THREAD

**Issue by LuciferSam86** [JTrotta/acme.sh#3]
Hi,
before I buy a domain from Aruba to test the APIs for acme.sh I would like to know if:
- If I buy a domain, the APIs are available even if I'm not a "business customer"?
- The link you put for the documentation is behind a login page on aruba business site.

**Comment by JTrotta** [comment]
If I buy a domain, the APIs are available even if I'm not a "business customer"? I do not think so.
